# Generated by Django 3.2.25 on 2024-09-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('random_image', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagecontainer',
            options={'ordering': ['start_date'], 'verbose_name': 'image', 'verbose_name_plural': 'images'},
        ),
        migrations.AlterField(
            model_name='imagecontainer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='imagecontainer',
            name='start_date',
            field=models.DateTimeField(verbose_name='start date'),
        ),
    ]
